import type { Metadata } from "next";
import { Titillium_Web, STIX_Two_Text } from "next/font/google";
import "./globals.css";

const titilliumWeb = Titillium_Web({
  variable: "--font-titillium-web",
  weight: "300",
  subsets: ["latin"],
});

const stixTwoText = STIX_Two_Text({
  variable: "--font-stix-two-text",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aayush Chhetri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${stixTwoText.className}  antialiased`}>
        <div className="bg-background mx-auto max-w-2xl md:max-w-3xl px-6">
          {children}
        </div>
      </body>
    </html>
  );
}
